[build]
    command = "npm run build"
    publish = "."

[[plugins]]
    package = "@netlify/plugin-local-install-core"

[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = true
    minify = true
[build.processing.js]
    bundle = true
    minify = true
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true

[build.environment]
    REACT_APP_BACKEND_URL = "https://mon-portfolio-backend.onrender.com"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200