   services:
     - type: web
       name: mon-portfolio-backend
       env: node
       buildCommand: npm install
       startCommand: node server.js
       envVars:
         - key: MONGODB_URI
           sync: false
         - key: JWT_SECRET
           sync: false